name: emoji-mashup
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pillow
  - pip:
    - streamlit>=1.22.0,<2.0.0
    - requests>=2.31.0,<3.0.0
    - transformers>=4.29.2,<5.0.0
    - torch>=1.13.0,<3.0.0
    - diffusers>=0.16.1,<0.17.0
